### ISSUE TITLE
Continious Indicator calculation

### ISSUE THREAD

**Issue by przemo098** [DaveSkender/Stock.Indicators#1034] opened 2023-02-22 10:47 UTC
Currently we have to calc everything from scratch.
However for long running systems it would be nice to have possibility to calc last RSI and after day start to calc next RSI from previous run.

**Comment by DaveSkender** [comment] 2023-02-22 17:44
Please follow #1018 to track our Streaming use case preview.  The streaming use case and the incremental calculation use case are actually the same.  Closing this since it's a duplicate of a larger v3 [roadmap objective](https://github.com/DaveSkender/Stock.Indicators/discussions/218).

**Closed by DaveSkender** 2023-02-22 17:44 UTC
Labels: enhancement
