### ISSUE TITLE
System.DivideByZeroException: Attempted to divide by zero.

### ISSUE THREAD

**Issue by sharpwood** [DaveSkender/Stock.Indicators#400] opened 2021-03-28 09:14 UTC
An exception occurred when i used Indicator.GetZigZag 

System.DivideByZeroException: Attempted to divide by zero.

**Comment by DaveSkender** [comment] 2021-03-28 15:58
Thanks for reporting, I'll take a look.  If convenient, please send the `history` that was used when this occurred.  I can add it to our bad data test scenarios.

**Comment by DaveSkender** [comment] 2021-03-28 16:47
Analysis: I did find a divide by zero opportunity in the code and am writing a fix to better handle it.  It looks like this would happen if the first quote in `history` has either a High, Low, or Close value of 0 (zero).

In your specific case, you may also want to check the data you are providing into the library to see if this is a source data problem or something else.

In any case, I'm fixing the bug to gracefully handle the situation.  With this bug fix and given the same `history` as before, you will get `null` results instead of an Exception.

**Comment by DaveSkender** [comment] 2021-03-28 18:31
This was potentially fixed in v1.10.4

With that said, if you do have the offending `history`, I can still add that to our bad test data cases and therefore will be able to verify that the exact bug was fixed.

**Comment by sharpwood** [comment] 2021-03-28 22:45
Now it doesn't report that mistake any more, but it's stuck. It's like it is in a dead circle.

**Comment by sharpwood** [comment] 2021-03-28 23:13
[data.zip](https://github.com/DaveSkender/Stock.Indicators/files/6218268/data.zip)

**Comment by DaveSkender** [comment] 2021-03-28 23:17
Yikes, made it worse!  I’ve deprecated v1.10.4 and will try again with your data; thanks for providing.

**Comment by DaveSkender** [comment] 2021-03-28 23:21
What parameter arguments are you using?

**Comment by sharpwood** [comment] 2021-03-28 23:56
GetZigZag(bars, ZigZagType.HighLow, 3);

**Comment by DaveSkender** [comment] 2021-03-29 00:05
Thank you.  I'm now able to reproduce and am trying to figure it out.  There's some sort of unexpected data scenario here that the code cannot handle (statement of obvious :neckbeard:).

**Comment by DaveSkender** [comment] 2021-03-29 00:22
This is pretty rare, glad you found it.  It looks like the error occurs when the first point in history of High/Low variant has a high and low value difference that exceeds the transition threshold.  It is both a High and Low pivot simultaneously, and it tries to draw a line between point 1 and point 1, which is basically impossible.  I think we'll call this the Schrodinger's ZigZag scenario.  :)

**Closed** 2021-03-29 00:57 UTC
Labels: bug

**Comment by DaveSkender** [comment] 2021-03-29 01:17
Ok, give 1.10.6 a try.  I think we got it right this time.
